# Generated by Django 3.1.6 on 2021-02-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPT', '0002_auto_20210222_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='spends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SPT.spendings'),
        ),
    ]
