# Generated by Django 3.1.6 on 2021-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPT', '0003_auto_20210222_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
