# Generated by Django 3.1.6 on 2021-02-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPT', '0004_auto_20210222_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendings',
            name='date',
        ),
        migrations.AddField(
            model_name='shares',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
