# Generated by Django 3.1.6 on 2021-02-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPT', '0006_auto_20210222_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
